import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from "react";
 
const inter = Inter({ subsets: ['latin'] })

function Paragraph(props) {
  return (
    <>
      <p> Daughli is awesome for making it this far in his coding journey! Congratulations!!      </p>
      <p>{props.id}:{props.title}</p>
    </>
  )
}

function Card(props) {
  const [likes, setLikes] = useState(0)

  if (likes == 0) {
    return (
      <div
        class="card col-4 d-flex justify-content-center"
      >
        <button
          onClick={() => {
            setLikes(likes + 1);
          }}
        >
          Click to reveal Pokemon
        </button>
      </div>
    );
  }

  return (
    <div
      class="card col-4 d-flex justify-content-center"
    >
      <div class="card">
        <img src={props.src} class="card-img-top" alt="..." />
        <div class="card-body">
          <Link href={{pathname: "pokemon/[id]", query: { id: props.id}}}>
          <a><h5 class="card-title">{props.title}</h5></a>
          </Link>
          <p class="card-text">{props.text}</p>
          {likes == 0 ? null : <p class="card-text">Likes {likes}</p>}
          {likes == 10 ? null : (
            <button onClick={() => { setLikes(likes + 1) }} href="#" class="btn btn-primary">
              {props.buttonText}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

function getIdFromPokemon(pokemon) {
  return pokemon.url.replace(
    "https://pokeapi.co/api/v2/pokemon/", ""
  ).replace("/", "")
}

function App() {
  const [pokemonList, setPokemonList] = useState([]);
  const [offset, setOffset] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const limit = 20;

  useEffect(() => {
    setIsLoading(true);
    fetch(`https://pokeapi.co/api/v2/pokemon?offset=${offset}&limit=${limit}`)
      .then(response => {
        return response.json();
      })
      .then(json => {
        setIsLoading(false);
        setPokemonList([...pokemonList, ...json["results"]]);
      })
  }, [offset])

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
      <Paragraph />
      <Paragraph title="This is a paragraph" id={1} />
      <Paragraph title="Code with Daughli" id={2} />
      <Paragraph title="Become a coding legend" id={3} />
      {/* <Card title="title" text="text" buttonText="Like" src="https://barrettjacksoncdn.azureedge.net/staging/carlist/items/Fullsize/Cars/228584/228584_Misc_655f5ac5-6fcf-4f0f-aa68-6906992bb31f_Web.jpg" />
      <Card title="2016 Bumblebee Camaro" text="Featured in The Last Knight: Transformers 4" buttonText="Like" src="https://barrettjacksoncdn.azureedge.net/staging/carlist/items/Fullsize/Cars/228584/228584_Misc_655f5ac5-6fcf-4f0f-aa68-6906992bb31f_Web.jpg" />
      <Card title="title" text="text" buttonText="Like" src="https://barrettjacksoncdn.azureedge.net/staging/carlist/items/Fullsize/Cars/228584/228584_Misc_655f5ac5-6fcf-4f0f-aa68-6906992bb31f_Web.jpg" />
      */}
      <div class="container">
        <div class="row">
          {pokemonList.map(pokemon => {            
            const id = getIdFromPokemon(pokemon);
            return <Card
              id={id}
              title={pokemon["name"]}
              text="text"
              buttonText="like"
              src={`https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`}
            />
          })}
        </div>
        {isLoading == true ? <div class="spinner-border" role="status">
          <span class="visually-hidden">Loading...</span>
        </div> : null}
        <div>
          <button onClick={() => { setOffset(offset + limit) }}> More
          </button>
        </div>
      </div>
    </div>
  );
}


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
